logging:
  level:
    org.springframework.web: INFO
    org.buding.weixin: DEBUG
    me.chanjar.weixin: DEBUG
wx:
  mp:
    configs:
      - appId: wx4bc99231e751c2b1
        secret: 6c3017634d5aa60dfe7d423e85102880
        token: 1qaz2wsx
        aesKey:
  templateMsg:
    touser: oJzCD55ZOaSCmdyua5rRaTpysUUA
    tmpid: GIXQWewxlSmAhALcIAr9Ca5ulhXvhpz0H32aBqVvk44
server:
  port: 80
